COUNTRY_SVG_MAP = {
    "Afghanistan": "af.svg",
    "Algeria": "dz.svg",
    "Argentina": "ar.svg",
    "Australia": "au.svg",
    "Austria": "at.svg",
    "Brazil": "br.svg",
    "Cambodia": "kh.svg",
    "Canada": "ca.svg",
    "Chile": "cl.svg",
    "China": "cn.svg",
    "Czech Republic": "cz.svg",
    "Ecuador": "ec.svg",
    "Egypt": "eg.svg",
    "Finland": "fi.svg",
    "France": "fr.svg",
    "Germany": "de.svg",
    "Ghana": "gh.svg",
    "Greece": "gr.svg",
    "Greenland": "gl.svg",
    "Honduras": "hn.svg",
    "Hong Kong": "hk.svg",
    "Hungary": "hu.svg",
    "Iceland": "is.svg",
    "India": "in.svg",
    "Indonesia": "id.svg",
    "Iraq": "iq.svg",
    "Ireland": "ie.svg",
    "Italy": "it.svg",
    "Jamaica": "jm.svg",
    "Japan": "jp.svg",
    "Jordan": "jo.svg",
    "Kenya": "ke.svg",
    "Kuwait": "kw.svg",
    "Latvia": "lv.svg",
    "Liberia": "lr.svg",
    "Lithuania": "lt.svg",
    "Madagascar": "mg.svg",
    "Malaysia": "my.svg",
    "Mali": "ml.svg",
    "Mexico": "mx.svg",
    "Mongolia": "mn.svg",
    "Morocco": "ma.svg",
    "Mozambique": "mz.svg",
    "Nepal": "np.svg",
    "Netherlands": "nl.svg",
    "New Zealand": "nz.svg",
    "Nigeria": "ng.svg",
    "Norway": "no.svg",
    "Pakistan": "pk.svg",
    "Panama": "pa.svg",
    "Paraguay": "py.svg",
    "Peru": "pe.svg",
    "Philippines": "ph.svg",
    "Poland": "pl.svg",
    "Portugal": "pt.svg",
    "Qatar": "qa.svg",
    "Romania": "ro.svg",
    "Russian Federation": "ru.svg",
    "Rwanda": "rw.svg",
    "Saudi Arabia": "sa.svg",
    "Senegal": "sn.svg",
    "South Africa": "za.svg",
    "Spain": "es.svg",
    "Sri Lanka": "lk.svg",
    "Sudan": "sd.svg",
    "Sweden": "se.svg",
    "Switzerland": "ch.svg",
    "Taiwan": "tw.svg",
    "Tanzania, United Republic of": "tz.svg",
    "Thailand": "th.svg",
    "Tunisia": "tn.svg",
    "Turkey": "tr.svg",
    "Uganda": "ug.svg",
    "Ukraine": "ua.svg",
    "United Arab Emirates": "ae.svg",
    "United Kingdom": "gb.svg",
    "Uruguay": "uy.svg",
    "Uzbekistan": "uz.svg",
    "Venezuela": "ve.svg",
    "Viet Nam": "vn.svg",
    "Yemen": "ye.svg",
    "Zimbabwe": "zw.svg"
}

COUNTRY_TO_REGION = {
    # Africa
    "Algeria": "Africa",
    "Egypt": "Africa",
    "Ghana": "Africa",
    "Kenya": "Africa",
    "Liberia": "Africa",
    "Madagascar": "Africa",
    "Mali": "Africa",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Nigeria": "Africa",
    "Rwanda": "Africa",
    "Senegal": "Africa",
    "South Africa": "Africa",
    "Sudan": "Africa",
    "Tanzania, United Republic of": "Africa",
    "Tunisia": "Africa",
    "Uganda": "Africa",
    "Zimbabwe": "Africa",

    # Asia
    "Afghanistan": "Asia",
    "Cambodia": "Asia",
    "China": "Asia",
    "Hong Kong": "Asia",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iraq": "Asia",
    "Japan": "Asia",
    "Jordan": "Asia",
    "Kuwait": "Asia",
    "Malaysia": "Asia",
    "Mongolia": "Asia",
    "Nepal": "Asia",
    "Pakistan": "Asia",
    "Philippines": "Asia",
    "Qatar": "Asia",
    "Russian Federation": "Asia",
    "Saudi Arabia": "Asia",
    "Sri Lanka": "Asia",
    "Taiwan": "Asia",
    "Thailand": "Asia",
    "Turkey": "Asia",
    "United Arab Emirates": "Asia",
    "Uzbekistan": "Asia",
    "Viet Nam": "Asia",
    "Yemen": "Asia",

    # Europe
    "Austria": "Europe",
    "Czech Republic": "Europe",
    "Finland": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Greece": "Europe",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "Ireland": "Europe",
    "Italy": "Europe",
    "Latvia": "Europe",
    "Lithuania": "Europe",
    "Netherlands": "Europe",
    "Norway": "Europe",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Romania": "Europe",
    "Spain": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Ukraine": "Europe",
    "United Kingdom": "Europe",

    # North America
    "Canada": "North America",
    "Greenland": "North America",
    "Honduras": "North America",
    "Jamaica": "North America",
    "Mexico": "North America",
    "Panama": "North America",

    # South America
    "Argentina": "South America",
    "Brazil": "South America",
    "Chile": "South America",
    "Ecuador": "South America",
    "Paraguay": "South America",
    "Peru": "South America",
    "Uruguay": "South America",
    "Venezuela": "South America",

    # Oceania
    "Australia": "Oceania",
    "New Zealand": "Oceania",
}

COUNTRIES = sorted(COUNTRY_SVG_MAP.keys())

ROUND_COUNT = 5
